// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

export type SupabaseEnvStatus = "ok" | "missing-url" | "missing-key" | "missing-both";

export function getSupabaseEnvStatus(): {
  status: SupabaseEnvStatus;
  missing: string[];
  url?: string;
  key?: string;
} {
  const SUPABASE_URL =
    (typeof import.meta !== "undefined" && (import.meta.env as Record<string, unknown> | undefined)?.["VITE_SUPABASE_URL"] as string | undefined) ||
    (typeof process !== "undefined" && (process.env as Record<string, unknown> | undefined)?.["SUPABASE_URL"] as string | undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" && (import.meta.env as Record<string, unknown> | undefined)?.["VITE_SUPABASE_PUBLISHABLE_KEY"] as string | undefined) ||
    (typeof process !== "undefined" && (process.env as Record<string, unknown> | undefined)?.["SUPABASE_PUBLISHABLE_KEY"] as string | undefined);

  const missing = [
    ...(!SUPABASE_URL ? ["SUPABASE_URL", "VITE_SUPABASE_URL"] : []),
    ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"] : []),
  ];
  let status: SupabaseEnvStatus = "ok";
  if (!SUPABASE_URL && !SUPABASE_PUBLISHABLE_KEY) status = "missing-both";
  else if (!SUPABASE_URL) status = "missing-url";
  else if (!SUPABASE_PUBLISHABLE_KEY) status = "missing-key";
  return { status, missing, url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY };
}

export function renderSupabaseSetupError(missing: string[]): string {
  const bullets = missing
    .map((k) => `  • ${k}`)
    .join("<br>");
  return `<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>إعدادات Supabase مطلوبة | أوبن لوب</title>
<style>
  *{box-sizing:border-box} html,body{margin:0;padding:0;font-family:Tajawal,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;background:#0d1921;color:#e6edf3}
  .wrap{min-height:100dvh;display:grid;place-items:center;padding:24px}
  .card{width:100%;max-width:640px;background:#13232e;border:1px solid #2F525788;border-radius:22px;padding:32px 28px;box-shadow:0 18px 60px rgba(0,0,0,.35)}
  .tag{display:inline-block;background:#E09F4822;color:#E09F48;border:1px solid #E09F4855;border-radius:999px;padding:4px 12px;font-size:12px;font-weight:800;letter-spacing:.3px}
  h1{margin:14px 0 6px;font-size:26px;line-height:1.3;color:#fff}
  p{margin:6px 0 18px;line-height:1.85;color:#b7c4cd}
  code{background:#0b151c;border:1px solid #2F525766;color:#E09F48;padding:3px 8px;border-radius:8px;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:13px}
  .missing{background:#C34A361A;border:1px dashed #C34A3666;border-radius:16px;padding:14px 18px;margin:10px 0 20px;color:#ffb8ad;font-weight:600;line-height:1.8}
  .steps{list-style:none;padding:0;margin:10px 0 0;counter-reset:s}
  .steps li{counter-increment:s;display:grid;grid-template-columns:40px 1fr;gap:12px;padding:12px 0;border-bottom:1px dashed #2F525744;align-items:start}
  .steps li:last-child{border-bottom:0}
  .steps li::before{content:counter(s);width:40px;height:40px;border-radius:50%;background:#2F525755;border:1px solid #2F525777;color:#9CD3D8;display:grid;place-items:center;font-weight:900;font-size:15px;flex:none}
  .steps b{color:#fff}
  .foot{margin-top:22px;padding-top:18px;border-top:1px solid #2F525744;display:flex;flex-wrap:wrap;gap:10px;align-items:center;justify-content:space-between}
  .hint{font-size:12px;color:#8fa2ab}
  .btn{display:inline-flex;align-items:center;gap:8px;border-radius:999px;background:#17374A;color:#fff;border:1px solid #2F525777;padding:10px 18px;font-weight:800;text-decoration:none}
  .btn.primary{background:#E09F48;color:#17374A;border-color:#E09F48}
  @media (max-width:520px){.card{padding:24px 20px} h1{font-size:22px}}
</style>
</head>
<body><div class="wrap"><div class="card">
  <span class="tag">⚠️ إعداد مطلوب قبل المتابعة</span>
  <h1>متغيرات Supabase مفقودة في بيئة النشر (Vercel)</h1>
  <p>رسالة <code>This page didn't load</code> التي تظهر لك سببها مباشر أن مفاتيح Supabase <b>لم تُضف بعد</b> إلى إعدادات Environment Variables في مشروع Vercel. الكود صحيح 100%، فقط يحتاج هذه البيانات.</p>
  <div class="missing">المتغيرات المفقودة حالياً:<br>${bullets}</div>
  <ol class="steps">
    <li><div><b>افتح إعدادات مشروعك في Vercel</b><br>المسار: Project → <code>Settings</code> → <code>Environment Variables</code></div></li>
    <li><div><b>انسخ القيم من ملف</b> <code>.env</code> الموجود على جهازك (أو من ملف <code>.env.example</code> في الريبو).<br>المطلوب إضافة <b>6 متغيرات</b> على الأقل: <code>SUPABASE_PROJECT_ID</code>، <code>SUPABASE_URL</code>، <code>SUPABASE_PUBLISHABLE_KEY</code>، <code>VITE_SUPABASE_PROJECT_ID</code>، <code>VITE_SUPABASE_URL</code>، <code>VITE_SUPABASE_PUBLISHABLE_KEY</code>. وأفضل تضيف أيضاً <code>SUPABASE_SERVICE_ROLE_KEY</code> لميزات الإدارة.</div></li>
    <li><div><b>حدّد البيئات الثلاثة لكل متغير</b>: <code>Production</code> + <code>Preview</code> + <code>Development</code> ثم اضغط <code>Save</code>.</div></li>
    <li><div><b>أعد نشر المشروع</b>: من تبويب <code>Deployments</code> → اضغط على النشر الأخير → <code>Redeploy</code> (مهم: مع تفعيل <code>Use existing Build Cache</code> خارق حتى تأخذ المتغيرات).</div></li>
  </ol>
  <div class="foot">
    <span class="hint">بمجرد إضافة المتغيرات وإعادة النشر، سيختفي هذا القسم وتحمل المنصة بشكل طبيعي.</span>
    <a class="btn primary" target="_blank" rel="noreferrer" href="https://vercel.com/docs/projects/environment-variables">دليل Vercel ↗</a>
  </div>
</div></div></body>
</html>`;
}

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient(): ReturnType<typeof createClient<Database>> | null {
  const { status, missing, url, key } = getSupabaseEnvStatus();
  if (status !== "ok") {
    const skipSetup =
      (typeof import.meta !== "undefined" &&
        ((import.meta.env as Record<string, unknown> | undefined)?.["VERCEL_SKIP_SSR_AUTH_BOOTSTRAP"] as string | undefined) === "1") ||
      (typeof process !== "undefined" &&
        ((process.env as Record<string, unknown> | undefined)?.["VERCEL_SKIP_SSR_AUTH_BOOTSTRAP"] as string | undefined) === "1");
    if (skipSetup) {
      console.warn("[Supabase] Environment variables missing but VERCEL_SKIP_SSR_AUTH_BOOTSTRAP=1 → returning null client (SSR-only graceful fallthrough).");
      return null;
    }
    // In SSR context, throw a dedicated marker so the server entry can render a friendly setup page
    // instead of the generic "This page didn't load" TanStack error boundary.
    const err = new Error(`Missing Supabase env vars: ${missing.join(", ")}`);
    (err as Error & { code?: string; missing?: string[] }).code = "SUPABASE_ENV_MISSING";
    (err as Error & { missing?: string[] }).missing = missing;
    throw err;
  }
  return createClient<Database>(url as string, key as string, {
    global: {
      fetch: createSupabaseFetch(key as string),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createClient<Database>> | null | undefined;
let _setupError: (Error & { code?: string; missing?: string[] }) | undefined;

export function getSupabaseSetupError(): (Error & { code?: string; missing?: string[] }) | undefined {
  return _setupError;
}

type PlaceholderChain = {
  (): PlaceholderChain;
  then: <T>(onfulfilled?: (value: unknown) => T | Promise<T>) => Promise<T | undefined>;
  select: PlaceholderChain;
  from: PlaceholderChain;
  auth: PlaceholderChain;
  rpc: PlaceholderChain;
  storage: PlaceholderChain;
  realtime: PlaceholderChain;
  channel: PlaceholderChain;
} & Record<string, PlaceholderChain>;

function buildNoopChain(message?: string): PlaceholderChain {
  // Deep no-op placeholder that returns itself for any property access / call.
  // Acts as a thenable so `await supabase.from(..).select(..)` always resolves.
  const chainInner = function () {
    return chain;
  } as unknown as PlaceholderChain;

  const chain = new Proxy(chainInner, {
    get(_t, p) {
      if (p === "then") {
        return (
          (onfulfilled?: ((value: unknown) => unknown) | null | undefined) => {
            try {
              const resolved = onfulfilled?.({
                data: null,
                error: new Error(message ?? "Supabase غير متاح حالياً"),
              });
              return Promise.resolve(resolved);
            } catch (e) {
              return Promise.reject(e);
            }
          }
        ) as unknown as PlaceholderChain["then"];
      }
      if (p === "catch") {
        return ((fn?: (reason: unknown) => unknown) => {
          return Promise.resolve(fn?.(new Error(message ?? "Supabase غير متاح حالياً")));
        }) as unknown as PlaceholderChain["catch"];
      }
      if (p === "finally") {
        return ((fn?: () => unknown) => {
          return Promise.resolve(fn?.());
        }) as unknown as PlaceholderChain["finally"];
      }
      return buildNoopChain(message);
    },
    apply(_t, _this, _args) {
      return chain;
    },
  }) as unknown as PlaceholderChain;
  return chain;
}

const NOOP_CLIENT_PLACEHOLDER = new Proxy({} as unknown as ReturnType<typeof createClient<Database>>, {
  get(_, prop) {
    return buildNoopChain("Supabase غير متاح حالياً (متغيرات البيئة مفقودة في Vercel).");
  },
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_, prop, receiver) {
    // NEVER throw on first access — never crash SSR page on Vercel.
    if (!_supabase) {
      try {
        _supabase = createSupabaseClient();
      } catch (err) {
        _setupError = err as Error & { code?: string; missing?: string[] };
        // Swallow bootstrap errors — return the no-op client so the page renders.
        // Pages will show appropriate user-friendly setup banners via useAuth().supabaseAvailable=false.
        console.warn(
          `[Supabase] Bootstrap failed — falling back to no-op placeholder. Missing vars: ${
            _setupError.missing?.join(", ") ?? _setupError.message ?? "unknown"
          }`,
        );
        _supabase = NOOP_CLIENT_PLACEHOLDER;
      }
    }
    if (!_supabase) {
      return Reflect.get(NOOP_CLIENT_PLACEHOLDER, prop, receiver);
    }
    return Reflect.get(_supabase, prop, receiver);
  },
});



